### ISSUE TITLE
This warehouse of yours is very interesting

### ISSUE THREAD

**Issue by FangSen9000** [seriouszyx/Digital-Image-Processing#2]
I want to know whether the image processing work comes from the laboratory of Henan University or the artificial intelligence laboratory. This is an interesting work. Does Henan University have such advanced teaching?

//I was the best undergraduate student in the computer department of Henan University. I was building GitHub organization of Henan University, so I saw this warehouse.

**Comment by seriouszyx** [comment]
These were just experiments for the digital image processing class in my junior year at [HENU](https://cs.henu.edu.cn/), taught by [Dr. Song](https://cs.henu.edu.cn/info/1048/1869.htm).
